# Generated by Django 3.1.3 on 2020-11-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20201105_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weather',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
