# Generated by Django 3.1.3 on 2020-11-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20201107_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weather_icon', to='weather.weather')),
            ],
        ),
    ]
