# Generated by Django 3.1.3 on 2020-11-29 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0005_weatherimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='user_account.account'),
            preserve_default=False,
        ),
    ]
