# Generated by Django 3.1.3 on 2020-11-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_weather_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weather',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
